api_key: ADD_HEAR_API_KEY
home_text: |
    Sputnik Navigation shows prices for many different tokens not only to $, but also to each other!
    
    To program Sputnik Navigation shows only tokens that you want:
    1) Send command /projects â€”> Bot will send you message with the list of tokens
    2) Reply to this message with the list of tokens that are need to be shown
    3) Enjoy actual prices for interesting pairs in one click!
    
    Sputnik Navigation is an add-on for p2p-exchange @SputnikNetworkBot

projects_text: "Enter the list of interesting projects in the chat, separated by commas. Names like in coingecko.Send 0 to delete the list. Reply to this message. Examples: "
projects_added: |
 Ok. Chat projects added.

help_text: |
    ğŸ›°ï¸ Sputnik Navigation ğŸ›°ï¸ is a part of the Sputnik Network - from Community for Community project of the Cosmos Ecosystem
    ğŸ›°ï¸ Sputnik Navigation ğŸ›°ï¸ shows the current prices for all pairs, that can be traded at p2p-exchange of the Sputnik Network
    
    ğŸ”¹ The actual price of tokens is taken from CoinGecko.com
    
    ğŸ”¹ To receive, send and exchange tokens - use \"Sputnik\" button, or follow the @SputnikNetworkBot
    
    ğŸ”¹ Video guide \"how to use the Sputnik: youtu.be/NwiI6xXkMcw
    
    ğŸ”¹ Add ğŸ›°ï¸ Sputnik Navigation ğŸ›°ï¸ to any Telegram-group, and members will have ability to get data on prices of the Cosmos Ecosystem tokens
    
    ğŸ”¹ If you have any questions, write to technical support: @SputnikNetwork
    
    Main group: @Sputnik_Network
    
    News channel: @SputnikDish
    
    Art channel: @TelescopeART
    
    Web: sputnik.exchange
    
    TW: twitter.com/SputnikNetwork

gas_text: "At what gas price should gwei send you a notification?  Send reply to this message. If you want to specify from-to, send it with a hyphen. For example, 25-35"

tokens: akash-network,band-protocol,binancecoin,bitcoin,certik,cosmos,crypto-com-chain,e-money,ethereum,fetch-ai,ion,iris-network,juno-network,kava,kava-lend,kava-swap,ki,likecoin,medibloc,mina-protocol,osmosis,persistence,regen,secret,sentinel,sifchain,solana,starname,terra-luna,terrausd,usdx,velas
tokens_sites: https://akash.network,https://bandprotocol.com/,https://binance.org,https://www.bitcoin.org/,https://www.certik.foundation/,https://cosmos.network,https://www.crypto.com/en/chain,https://e-money.com/,https://www.ethereum.org/,https://fetch.ai/,https://osmosis.zone/,https://www.irisnet.org/,https://junochain.com/,https://kava.io,https://kava.io/lend,https://www.kava.io/swap,https://foundation.ki/,https://like.co/,https://medibloc.org/,https://minaprotocol.com/,https://app.osmosis.zone,https://persistence.one/,https://www.regen.network/mainnet,https://scrt.network,https://sentinel.co/,https://sifchain.finance/,https://solana.com/,https://starname.me,https://terra.money/,https://terra.money/,https://www.kava.io/overview,https://www.velas.com/
image_path: https://dpos.space/cosmos-prices/images/