api_key: ADD_HEAR_API_KEY
home_text: |
    Sputnik Navigation Bot shows you market prices of pairs, that can be created with:
    $ATOM ğŸ”¹ $KAVA ğŸ”¹ $IOV ğŸ”¹
    $HARD ğŸ”¹ $USDX ğŸ”¹ $SCRT ğŸ”¹
    
    P2P-exchange bot for the Cosmos Ecosystem: @SputnikNetworkBot

projects_text: "Enter the list of interesting projects in the chat, separated by commas. Names like in coingecko.Send 0 to delete the list. Reply to this message. Examples: "
projects_added: |
 Ok. Chat projects added.

help_text: |
    ğŸ›°ï¸ Sputnik Navigation ğŸ›°ï¸ is a part of the Sputnik Network - from Community for Community project of the Cosmos Ecosystem
    ğŸ›°ï¸ Sputnik Navigation ğŸ›°ï¸ shows the current prices for all pairs, that can be traded at p2p-exchange of the Sputnik Network
    
    ğŸ”¹ The actual price of tokens is taken from CoinGecko.com
    
    ğŸ”¹ To receive, send and exchange tokens - use \"Sputnik\" button, or follow the @SputnikNetworkBot
    
    ğŸ”¹ Video guide \"how to use the Sputnik: youtu.be/NwiI6xXkMcw
    
    ğŸ”¹ Add ğŸ›°ï¸ Sputnik Navigation ğŸ›°ï¸ to any Telegram-group, and members will have ability to get data on prices of the Cosmos Ecosystem tokens
    
    ğŸ”¹ If you have any questions, write to technical support: @SputnikNetwork
    
    Main group: @Sputnik_Network
    
    News channel: @SputnikDish
    
    Art channel: @TelescopeART
    
    Web: sputnik.exchange
    
    TW: twitter.com/SputnikNetwork

tokens: akash-network,band-protocol,binancecoin,certik,cosmos,crypto-com-chain,fetch-ai,hard-protocol,ion,iris-network,kava,ki,mina-protocol,osmosis,persistence,regen,secret,sentinel,sifchain,solana,starname,terra-luna,usdx
tokens_sites: https://akash.network,https://bandprotocol.com/,https://binance.org,https://www.certik.foundation/,https://cosmos.network,https://www.crypto.com/en/chain,https://fetch.ai/,https://www.kava.io/hard-protocol,https://ionomy.com/,https://www.irisnet.org/,https://kava.io,https://foundation.ki/,https://minaprotocol.com/,https://app.osmosis.zone,https://persistence.one/,https://www.regen.network/mainnet,https://scrt.network,https://sentinel.co/,https://sifchain.finance/,https://solana.com/,https://starname.me,https://terra.money/,https://www.kava.io/overview
image_path: https://dpos.space/cosmos-prices/images/